// BlueyOS Multi-User System - passwd + shadow implementation
// "Who's playing today?" - Bluey
// Users: bandit (root), bluey, bingo, chilli, jack, judo
//
// Password policy note: passwords use PBKDF2-SHA256 with a work factor.
// For a production OS, use bcrypt or argon2id with memory-hard settings.
// This is a research/learning OS - see SECURITY.md for full details.
//
// Bluey and all related characters are trademarks of Ludo Studio Pty Ltd,
// licensed by BBC Studios. BlueyOS is an unofficial fan/research project.
#include "../include/types.h"
#include "../include/bluey.h"
#include "../lib/string.h"
#include "../lib/stdio.h"
#include "multiuser.h"
#include "password.h"
#include "process.h"

// ---------------------------------------------------------------------------
// Static user table (pre-loaded; no VFS dependency at boot)
// Format mirrors /etc/passwd: username:x:uid:gid:gecos:home:shell
// ---------------------------------------------------------------------------
static passwd_entry_t passwd_table[] = {
    /* username,   uid, gid, gecos,                    home,           shell     */
    { "bandit",    0,   0,   "Bandit Heeler (Root)",   "/root",        "/bin/sh" },
    { "bluey",     1,   1,   "Bluey Heeler",           "/home/bluey",  "/bin/sh" },
    { "bingo",     2,   1,   "Bingo Heeler",           "/home/bingo",  "/bin/sh" },
    { "chilli",    3,   1,   "Chilli Heeler",          "/home/chilli", "/bin/sh" },
    { "jack",      4,   2,   "Jack (Bluey's mate)",    "/home/jack",   "/bin/sh" },
    { "judo",      5,   2,   "Judo",                   "/home/judo",   "/bin/sh" },
};
static const int PASSWD_COUNT = (int)(sizeof(passwd_table)/sizeof(passwd_table[0]));

// ---------------------------------------------------------------------------
// Shadow table: pre-computed PBKDF2-SHA256 salted hashes
// Passwords: bandit="bandit2dad", bluey="woohoo123", bingo="reddog456"
// chilli="mum4ever!", jack="snorkel99", judo="flip2win"
//
// Hash format: $pbkdf2-sha256$<iters>$<32 hex salt>$<64 hex hash>
// Generated by: password_hash_pbkdf2(pw, salt, iters, out)
//
// SECURITY NOTE: These are hardcoded defaults for a research OS.
// A real system must force password changes on first login and never ship
// with known-good passwords in source code.
// ---------------------------------------------------------------------------
static shadow_entry_t shadow_table[] = {
    /* username, hash (PBKDF2), last_changed, min, max, warn */
    { "bandit",
      "$pbkdf2-sha256$10000$"
      "3f1b7c6d9a82e5f00123456789abcdef$"
      "c913af6ad2b2b64d91860be8b97193c4"
      "5c49d0eeef356866204251c49c8410d7",
      0, 0, 99999, 7 },
    { "bluey",
      "$pbkdf2-sha256$10000$"
      "7d9f4a1e0c0b5f6e1122334455667788$"
      "f5f07c6926875023aedfd2087b52e1dc"
      "a0c596b16e7d3a360ac744eec25720f5",
      0, 0, 99999, 7 },
    { "bingo",  "!", 0, 0, 99999, 7 },   /* locked - "Bingo's not old enough!" */
    { "chilli", "*", 0, 0, 99999, 7 },   /* no password set - she just walks in */
    { "jack",   "*", 0, 0, 99999, 7 },
    { "judo",   "*", 0, 0, 99999, 7 },
};

static group_entry_t group_table[] = {
    { "root",  0, { "bandit", "" } },
    { "heelers", 1, { "bluey", "bingo", "chilli", "bandit", "" } },
    { "mates", 2, { "jack", "judo", "" } },
};
static const int GROUP_COUNT = (int)(sizeof(group_table) / sizeof(group_table[0]));

// Current session credentials
static uint32_t current_uid = 0;
static uint32_t current_gid = 0;

void multiuser_init(void) {
    kprintf("%s\n", MSG_USER_INIT);
    kprintf("[USR]  Users: ");
    for (int i = 0; i < PASSWD_COUNT; i++) {
        kprintf("%s(uid=%d)", passwd_table[i].username, passwd_table[i].uid);
        if (i < PASSWD_COUNT - 1) kprintf(", ");
    }
    kprintf("\n");
    // Start as root (bandit) at boot
    current_uid = 0;
    current_gid = 0;
}

int multiuser_authenticate(const char *username, const char *password) {
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (strcmp(passwd_table[i].username, username) != 0) continue;
        const char *hash = shadow_table[i].hash;
        if (strcmp(hash, "*") == 0) return 1;   /* no password set */
        if (strcmp(hash, "!") == 0) return 0;   /* account locked */
        return password_verify(password, hash);
    }
    return 0; /* unknown user */
}

int multiuser_login(const char *username, const char *password,
                    uint32_t *uid_out, uint32_t *gid_out) {
    if (!multiuser_authenticate(username, password)) return -1;
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (strcmp(passwd_table[i].username, username) == 0) {
            *uid_out = passwd_table[i].uid;
            *gid_out = passwd_table[i].gid;
            current_uid = passwd_table[i].uid;
            current_gid = passwd_table[i].gid;
            return 0;
        }
    }
    return -1;
}

int multiuser_get_passwd(uint32_t uid, passwd_entry_t *out) {
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (passwd_table[i].uid == uid) {
            *out = passwd_table[i];
            return 0;
        }
    }
    return -1;
}

int multiuser_get_passwd_by_name(const char *name, passwd_entry_t *out) {
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (strcmp(passwd_table[i].username, name) == 0) {
            *out = passwd_table[i];
            return 0;
        }
    }
    return -1;
}

int multiuser_is_user_in_group(uint32_t uid, uint32_t gid) {
    passwd_entry_t passwd;
    if (multiuser_get_passwd(uid, &passwd) == 0 && passwd.gid == gid) return 1;

    const char *username = NULL;
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (passwd_table[i].uid == uid) {
            username = passwd_table[i].username;
            break;
        }
    }
    if (!username) return 0;

    for (int i = 0; i < GROUP_COUNT; i++) {
        if (group_table[i].gid != gid) continue;
        for (int m = 0; m < MAX_GROUP_MEMBERS; m++) {
            if (group_table[i].members[m][0] == '\0') break;
            if (strcmp(group_table[i].members[m], username) == 0) return 1;
        }
    }
    return 0;
}

size_t multiuser_get_groups(uint32_t uid, uint32_t gid, uint32_t *out, size_t max) {
    size_t count = 0;
    if (!out || max == 0) return 0;

    out[count++] = gid;

    for (int i = 0; i < GROUP_COUNT && count < max; i++) {
        if (group_table[i].gid == gid) continue;
        if (!multiuser_is_user_in_group(uid, group_table[i].gid)) continue;
        out[count++] = group_table[i].gid;
    }
    return count;
}

uint32_t multiuser_current_uid(void) {
    process_t *process = process_current();
    if (process) return process->euid;
    return current_uid;
}

uint32_t multiuser_current_gid(void) {
    process_t *process = process_current();
    if (process) return process->egid;
    return current_gid;
}

void multiuser_set_current(uint32_t uid, uint32_t gid) {
    current_uid = uid;
    current_gid = gid;
}

int multiuser_is_root(void) { return multiuser_current_uid() == 0; }

void multiuser_print_passwd(void) {
    kprintf("# /etc/passwd\n");
    for (int i = 0; i < PASSWD_COUNT; i++) {
        passwd_entry_t *p = &passwd_table[i];
        kprintf("%s:x:%d:%d:%s:%s:%s\n",
                p->username, p->uid, p->gid, p->gecos, p->home, p->shell);
    }
}

void multiuser_print_shadow(void) {
    kprintf("# /etc/shadow (hashes shown - keep this file 000 root root!)\n");
    for (int i = 0; i < PASSWD_COUNT; i++) {
        shadow_entry_t *s = &shadow_table[i];
        kprintf("%s:%s:%d:%d:%d:%d:::\n",
                s->username, s->hash, s->last_changed,
                s->min_age, s->max_age, s->warn_days);
    }
}
