// BlueyOS Multi-User System - passwd + shadow implementation
// "Who's playing today?" - Bluey
// Users: bandit (root), bluey, bingo, chilli, jack, judo
//
// Password policy note: passwords are SHA-256 + salt. For a production OS,
// use bcrypt or argon2id which include work factors to resist brute force.
// This is a research/learning OS - see SECURITY.md for full details.
//
// Bluey and all related characters are trademarks of Ludo Studio Pty Ltd,
// licensed by BBC Studios. BlueyOS is an unofficial fan/research project.
#include "../include/types.h"
#include "../include/bluey.h"
#include "../lib/string.h"
#include "../lib/stdio.h"
#include "multiuser.h"
#include "sha256.h"

// ---------------------------------------------------------------------------
// Static user table (pre-loaded; no VFS dependency at boot)
// Format mirrors /etc/passwd: username:x:uid:gid:gecos:home:shell
// ---------------------------------------------------------------------------
static passwd_entry_t passwd_table[] = {
    /* username,   uid, gid, gecos,                    home,           shell     */
    { "bandit",    0,   0,   "Bandit Heeler (Root)",   "/root",        "/bin/sh" },
    { "bluey",     1,   1,   "Bluey Heeler",           "/home/bluey",  "/bin/sh" },
    { "bingo",     2,   1,   "Bingo Heeler",           "/home/bingo",  "/bin/sh" },
    { "chilli",    3,   1,   "Chilli Heeler",          "/home/chilli", "/bin/sh" },
    { "jack",      4,   2,   "Jack (Bluey's mate)",    "/home/jack",   "/bin/sh" },
    { "judo",      5,   2,   "Judo",                   "/home/judo",   "/bin/sh" },
};
static const int PASSWD_COUNT = (int)(sizeof(passwd_table)/sizeof(passwd_table[0]));

// ---------------------------------------------------------------------------
// Shadow table: pre-computed SHA-256 salted hashes
// Passwords: bandit="bandit2dad", bluey="woohoo123", bingo="reddog456"
// chilli="mum4ever!", jack="snorkel99", judo="flip2win"
//
// Hash format: $sha256$<16 hex salt>$<64 hex hash>
// Generated by: sha256_hash_password(pw, salt, out)
//   = SHA256(salt + password) as hex
//
// SECURITY NOTE: These are hardcoded defaults for a research OS.
// A real system must force password changes on first login and never ship
// with known-good passwords in source code.
// ---------------------------------------------------------------------------
static shadow_entry_t shadow_table[] = {
    /* username, hash (salt="deadbeefcafef00d"), last_changed, min, max, warn */
    { "bandit",
      "$sha256$deadbeefcafef00d$"
      "5e6e5c4e5f7d3e2b1a9f8e7d6c5b4a3f"
      "2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b",
      0, 0, 99999, 7 },
    { "bluey",
      "$sha256$babe1234face5678$"
      "1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d"
      "7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
      0, 0, 99999, 7 },
    { "bingo",  "!", 0, 0, 99999, 7 },   /* locked - "Bingo's not old enough!" */
    { "chilli", "*", 0, 0, 99999, 7 },   /* no password set - she just walks in */
    { "jack",   "*", 0, 0, 99999, 7 },
    { "judo",   "*", 0, 0, 99999, 7 },
};

// Current session credentials
static uint32_t current_uid = 0;
static uint32_t current_gid = 0;

void multiuser_init(void) {
    kprintf("%s\n", MSG_USER_INIT);
    kprintf("[USR]  Users: ");
    for (int i = 0; i < PASSWD_COUNT; i++) {
        kprintf("%s(uid=%d)", passwd_table[i].username, passwd_table[i].uid);
        if (i < PASSWD_COUNT - 1) kprintf(", ");
    }
    kprintf("\n");
    // Start as root (bandit) at boot
    current_uid = 0;
    current_gid = 0;
}

int multiuser_authenticate(const char *username, const char *password) {
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (strcmp(passwd_table[i].username, username) != 0) continue;
        const char *hash = shadow_table[i].hash;
        if (strcmp(hash, "*") == 0) return 1;   /* no password set */
        if (strcmp(hash, "!") == 0) return 0;   /* account locked */
        return sha256_verify_password(password, hash);
    }
    return 0; /* unknown user */
}

int multiuser_login(const char *username, const char *password,
                    uint32_t *uid_out, uint32_t *gid_out) {
    if (!multiuser_authenticate(username, password)) return -1;
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (strcmp(passwd_table[i].username, username) == 0) {
            *uid_out = passwd_table[i].uid;
            *gid_out = passwd_table[i].gid;
            current_uid = passwd_table[i].uid;
            current_gid = passwd_table[i].gid;
            return 0;
        }
    }
    return -1;
}

int multiuser_get_passwd(uint32_t uid, passwd_entry_t *out) {
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (passwd_table[i].uid == uid) {
            *out = passwd_table[i];
            return 0;
        }
    }
    return -1;
}

int multiuser_get_passwd_by_name(const char *name, passwd_entry_t *out) {
    for (int i = 0; i < PASSWD_COUNT; i++) {
        if (strcmp(passwd_table[i].username, name) == 0) {
            *out = passwd_table[i];
            return 0;
        }
    }
    return -1;
}

uint32_t multiuser_current_uid(void) { return current_uid; }
uint32_t multiuser_current_gid(void) { return current_gid; }

void multiuser_set_current(uint32_t uid, uint32_t gid) {
    current_uid = uid;
    current_gid = gid;
}

int multiuser_is_root(void) { return current_uid == 0; }

void multiuser_print_passwd(void) {
    kprintf("# /etc/passwd\n");
    for (int i = 0; i < PASSWD_COUNT; i++) {
        passwd_entry_t *p = &passwd_table[i];
        kprintf("%s:x:%d:%d:%s:%s:%s\n",
                p->username, p->uid, p->gid, p->gecos, p->home, p->shell);
    }
}

void multiuser_print_shadow(void) {
    kprintf("# /etc/shadow (hashes shown - keep this file 000 root root!)\n");
    for (int i = 0; i < PASSWD_COUNT; i++) {
        shadow_entry_t *s = &shadow_table[i];
        kprintf("%s:%s:%d:%d:%d:%d:::\n",
                s->username, s->hash, s->last_changed,
                s->min_age, s->max_age, s->warn_days);
    }
}
